### ISSUE TITLE
Unable to install Zerotier as usual nor upgrade is possible

### ISSUE THREAD

**Issue by yashodhank** [YunoHost-Apps/zerotier_ynh#38] opened 2023-04-03 00:33 UTC
### Describe the bug

Unable to install after failed upgrade and clean removal of zerotier from system.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.15
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: stable / master

### Steps to reproduce

Try to install application as usual from webadmin UI or CLI you will get error as follows:

### Expected behavior

As there was some issue with older version zerotier does not allow Installations should succeed with latest version of zerotier.

### Logs
https://paste.yunohost.org/raw/afufuderiq

**Comment by tituspijean** [comment] 2023-04-03 10:44
Duplicate of #32

**Closed by tituspijean** 2023-04-03 10:44 UTC
